feat(articles): ab#54 add articles page markup
neokaidan/neokaidan-front pull request #2
Opened 2023-04-16 13:58 UTC by Helarioss

2023-04-16 14:05 UTC, mamonten0k commented on src/components/Card/Card.tsx
> +        <li className="cards__item">
Элемент списка лучше вынести в родительский компонент, карточка не знает, что она элемент списка

2023-04-16 14:06 UTC, mamonten0k commented on src/components/Cards/Cards.tsx
> +                <Card key={card.id} {...card} />
Наверное наши айдишники уникальны, но на всякий случай, есть крутая библа uuid, 
Импортищь {v4 as uuid} from uuid и можешь ключи ей делать

2023-04-16 14:10 UTC, mamonten0k commented on src/components/Search/Search.tsx
> +function Search() {
у нас будет много таких серчбаров, можно чуть специфичнее компонент назвать, например, SearchBar - базовый серчбар принимающий пропсами все что ему нужно, а в родительских - SearchArticles, обзываем его как пользовательское действие, определяем в нем функции для управления состоянием инпута и передаем их в SearchBar

2023-04-16 14:12 UTC, mamonten0k commented on src/components/Tag/Tag.tsx
> +import { Tag as ITag } from "src/types/Tag";
Норма объявлять интерфейсы и типы пропсов рядом с компонентом, выносят часто типы для апи или стора

2023-04-16 14:17 UTC, mamonten0k reviewed
Хороший код, оставил небольшие комментарии по коду

2023-04-17 18:06 UTC, Aruko21 requested changes
Отличный код, спасибо! Просьба пофиксить проблемы с табами в package.json и в webpack.config и можно будет сливать. Остальные фиксы по мере возможности

2023-04-17 18:06 UTC, Aruko21 commented on package.json
> +    "name": "neokaidan-front",
Проверь, пожалуйста, что твоя IDE подсосала .editorconfig. У package.json таб состоит из 2-х пробелов. Твоя IDE поменяла на 4

2023-04-17 18:06 UTC, Aruko21 commented on src/components/ArticlesEnd/ArticlesEnd.scss
> +.end__pre-eye {
Почему бы не вложить этот селектор в прошлый через & ?

2023-04-17 18:06 UTC, Aruko21 commented on src/components/ArticlesEnd/ArticlesEnd.tsx
> +function ArticlesEnd() {
Придирка до пустоты, но просьба после импортов 2 пустые строки оставлять. Это негласное соглашение почти во всех языках

2023-04-17 18:06 UTC, Aruko21 commented on src/components/ArticlesEnd/ArticlesEnd.tsx
> +        <div className="end">
Не критично, но стоит давать более информативные названия классам. Пусть даже они будут длинными. В данном случае я бы назвал этот блок как end-articles-notify или же, если у нас будет эта заглушка переиспользоваться для другого типа контента, то end-items-notify

2023-04-17 18:06 UTC, Aruko21 commented on src/components/ArticlesEnd/ArticlesEnd.tsx
> +            </picture>
Круто, что используешь такую подгрузку изображений!

2023-04-17 18:06 UTC, Aruko21 commented on src/components/Card/Card.scss
> +.cards__item {
Т.к. в качестве методологии нэйминга css мы используем БЭМ — стоит все связанное с cards держать в одном файле и использовать наследование SCSS с его операторами &

2023-04-17 18:06 UTC, Aruko21 commented on src/components/Card/Card.scss
> +.cards__overlay {
Для SCSS в целом советую пользоваться подходом: если у двух и более классов одинаковый префикс — выносить его наверх, а внутри писать селекторы через &. В контексте БЭМа это еще и на его логику ложится, что в начале у тебя Блок, а потом по вложенности элементы и модификаторы

2023-04-17 18:06 UTC, Aruko21 commented on src/components/Card/Card.scss
> +    color: #ffffff;
У нас для белого цвета есть переменная --white. Просьба для всех цветов в проекте использовать var(). Если цвета раньше не было — выносить его в __global

2023-04-17 18:06 UTC, Aruko21 commented on src/components/Card/Card.scss
> +    @media (any-hover: hover) {
Я такими медиа-запросами не пользовался, поэтому могу не понимать чего-то, но разве имеет смысл писать такой медиа для hover, если устройства, не обладающие возможностью наводить указатель, не смогут применить эти стили в прицнипе? Т.е. если написать .cards__link:hover и .cards__link:focus без media — то ничего не изменится. Устройства без ховера и так не смогут заюзать их

2023-04-17 18:06 UTC, Aruko21 commented on package.json
> +        "react-masonry-css": "^1.0.16",
Просьба по-возможности писать в наш README зачем был добавлен тот или иной пакет и что он делает

2023-04-17 18:06 UTC, Aruko21 commented on src/components/Card/Card.scss
> +    max-width: 100%;
Зачем max-width, если ниже width с тем же значением?

2023-04-17 18:06 UTC, Aruko21 commented on src/components/Card/Card.scss
> +    font-weight: 400;
Всю типографию нужно будет вынести в миксины SCSS. Это править сейчас не надо и я или Иван сделаем попозже

2023-04-17 18:06 UTC, Aruko21 commented on src/components/Card/Card.tsx
> +        <li className="cards__item">
Также мне кажется, что Card лучше поменять на ArticleCard, т.к. данный компонент не будет переиспользоваться где-то еще и содержит логику конкретно для карточки статьи, а не карточки в целом как компонента material design

2023-04-17 18:06 UTC, Aruko21 commented on src/components/Statistics/Statistics.tsx
> +interface StatisticsProps {
Аналогично не interface, а type

2023-04-17 18:06 UTC, Aruko21 commented on src/components/Cards/Cards.tsx
> +interface CardsProps {
Корректнее использовать type, а не interface. Интерфейс — это скелет класса с методами, который кто-то (класс) реализует. А тип — это пользовательский тип данных, используемый для того, чтобы одним словом обозвать какую-то непростую структуру

2023-04-17 18:06 UTC, Aruko21 commented on src/components/Tag/Tag.scss
> +    &--orange {
Эта отличный пример того, где нужно применять модификаторы по БЭМу :) Замени, пожалуйста --orange на _orange (с одним дэшэм) и так далее ниже

2023-04-17 18:06 UTC, Aruko21 commented on src/components/Tags/Tags.tsx
> +interface TagsProps {
Аналогично не interface, а type

2023-04-17 18:06 UTC, Aruko21 commented on src/types/Article.ts
> +export interface Article {
Аналогично не interface, а type

2023-04-17 18:06 UTC, Aruko21 commented on src/types/Tag.ts
> +export interface Tag {
Аналогично не interface, а type

2023-04-17 18:06 UTC, Aruko21 commented on src/types/Tag.ts
> +    color?: string;
Сейчас норм, но на будущее надо будет поменять колор на tagType и подтягивать цвет тэга либо из какой-то нашей мапы, либо с бэка

2023-04-17 18:06 UTC, Aruko21 commented on webpack.config.js
> +	devtool: "source-map",
Проверь, пожалуйста, что твоя IDE подсосала .editorconfig. У webpack.config таб состоит из 4-х пробелов. Кажется, что твоя IDE заменила их на табы из 8-ми пробелов О_о

2023-04-28 16:12 UTC, Helarioss commented on src/components/Card/Card.scss
> +    @media (any-hover: hover) {
При таче с мобильного устройства ховер всё равно срабатывает

2023-04-28 16:13 UTC, Helarioss commented on src/components/Card/Card.scss
> +    @media (any-hover: hover) {
> Я такими медиа-запросами не пользовался, поэтому могу не понимать чего-то, но разве имеет смысл писать такой медиа для hover, если устройства, не обладающие возможностью наводить указатель, не смогут применить эти стили в прицнипе? Т.е. если написать .cards__link:hover и .cards__link:focus без media — то ничего не изменится. Устройства без ховера и так не смогут заюзать их

При таче с мобильного устройства ховер всё равно срабатывает

2023-04-28 16:20 UTC, Helarioss commented on src/components/Card/Card.scss
> +    max-width: 100%;
> Зачем max-width, если ниже width с тем же значением?

Чтобы изображение не растягивалось больше своего исходного размера. Если исходный размер изображения 200px - его нельзя будет сделать 300px, и качество изображения не упадет

2023-04-28 21:08 UTC, mamonten0k approved these changes

2023-04-30 19:30 UTC, Aruko21 approved these changes

2023-04-30 19:30 UTC, merged